/* automatically generated by rust-bindgen 0.69.4 */

pub const OPENAPTX_MAJOR: u32 = 0;
pub const OPENAPTX_MINOR: u32 = 2;
pub const OPENAPTX_PATCH: u32 = 1;
pub type wchar_t = ::std::os::raw::c_int;
#[repr(C)]
#[repr(align(16))]
#[derive(Debug, Copy, Clone)]
pub struct max_align_t {
    pub __clang_max_align_nonce1: ::std::os::raw::c_longlong,
    pub __bindgen_padding_0: u64,
    pub __clang_max_align_nonce2: u128,
}
#[test]
fn bindgen_test_layout_max_align_t() {
    const UNINIT: ::std::mem::MaybeUninit<max_align_t> = ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<max_align_t>(),
        32usize,
        concat!("Size of: ", stringify!(max_align_t))
    );
    assert_eq!(
        ::std::mem::align_of::<max_align_t>(),
        16usize,
        concat!("Alignment of ", stringify!(max_align_t))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).__clang_max_align_nonce1) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(max_align_t),
            "::",
            stringify!(__clang_max_align_nonce1)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).__clang_max_align_nonce2) as usize - ptr as usize },
        16usize,
        concat!(
            "Offset of field: ",
            stringify!(max_align_t),
            "::",
            stringify!(__clang_max_align_nonce2)
        )
    );
}
extern "C" {
    pub static aptx_major: ::std::os::raw::c_int;
}
extern "C" {
    pub static aptx_minor: ::std::os::raw::c_int;
}
extern "C" {
    pub static aptx_patch: ::std::os::raw::c_int;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct aptx_context {
    _unused: [u8; 0],
}
extern "C" {
    pub fn aptx_init(hd: ::std::os::raw::c_int) -> *mut aptx_context;
}
extern "C" {
    pub fn aptx_reset(ctx: *mut aptx_context);
}
extern "C" {
    pub fn aptx_finish(ctx: *mut aptx_context);
}
extern "C" {
    pub fn aptx_encode(
        ctx: *mut aptx_context,
        input: *const ::std::os::raw::c_uchar,
        input_size: usize,
        output: *mut ::std::os::raw::c_uchar,
        output_size: usize,
        written: *mut usize,
    ) -> usize;
}
extern "C" {
    pub fn aptx_encode_finish(
        ctx: *mut aptx_context,
        output: *mut ::std::os::raw::c_uchar,
        output_size: usize,
        written: *mut usize,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn aptx_decode(
        ctx: *mut aptx_context,
        input: *const ::std::os::raw::c_uchar,
        input_size: usize,
        output: *mut ::std::os::raw::c_uchar,
        output_size: usize,
        written: *mut usize,
    ) -> usize;
}
extern "C" {
    pub fn aptx_decode_sync(
        ctx: *mut aptx_context,
        input: *const ::std::os::raw::c_uchar,
        input_size: usize,
        output: *mut ::std::os::raw::c_uchar,
        output_size: usize,
        written: *mut usize,
        synced: *mut ::std::os::raw::c_int,
        dropped: *mut usize,
    ) -> usize;
}
extern "C" {
    pub fn aptx_decode_sync_finish(ctx: *mut aptx_context) -> usize;
}
