[package]
name = "serve"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
dbus = "0.9.7"
env_logger = "0.11.3"
libpulse-binding = "2.28.1"
libpulse-simple-binding = "2.28.1"
log = "0.4.21"
